name: Selenium Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install google-chrome-stable
        
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f1)
        echo "Detected Chrome version: $CHROME_VERSION"
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION"
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Add Chromedriver to PATH
      run: echo "$(pwd)" >> $GITHUB_PATH


    - name: Verify Chrome and ChromeDriver installation
      run: |
        which google-chrome || echo "Chrome not found!"
        which chromedriver || echo "Chromedriver not found!"
        google-chrome --version
        chromedriver --version




        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest
        
    - name: Debug directory
      run: |
        pwd
        ls -la
        ls -la tests/
        
    - name: Run Selenium tests
      run: |
        python -m pytest tests/test_selenium.py -v --tb=long